"""Ada Core API — AgentBlueprint Schema.

The AgentBlueprint is Ada's "personality design document".
It captures all configuration that defines how an agent instance behaves:
persona, priority weights, model selection, tools, and quality settings.

Blueprints are versioned and tenant-scoped, enabling:
- A/B testing between blueprint versions
- Rollback to previous configurations
- Per-tenant customization without code changes

WHITEPAPER ref: Section 2 — Lifecycle Layer, Section 4 — Priority Weights
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field


class PriorityWeights(BaseModel):
    """Priority weights for strategy decisions.

    Higher weight = more important. Sum should be ~1.0.
    WHITEPAPER: Quality > Efficiency > Speed > Lightweight
    """

    quality: float = Field(default=0.4, ge=0.0, le=1.0)
    efficiency: float = Field(default=0.3, ge=0.0, le=1.0)
    speed: float = Field(default=0.2, ge=0.0, le=1.0)
    cost: float = Field(default=0.1, ge=0.0, le=1.0)

    def to_dict(self) -> dict[str, float]:
        return {
            "quality": self.quality,
            "efficiency": self.efficiency,
            "speed": self.speed,
            "cost": self.cost,
        }


class AgentBlueprint(BaseModel):
    """Ada's personality design document.

    Defines the complete configuration for an agent instance.
    Generated by the Lifecycle Layer (scribe) and consumed by
    the Execution Layer (strategist).

    Attributes:
        id: Unique blueprint identifier
        tenant_id: Owning tenant
        version: Auto-incremented version number
        name: Human-readable blueprint name
        persona: Persona definition (role, tone, expertise)
        system_prompt: Dynamically generated system prompt
        priority_weights: Quality/Efficiency/Speed/Cost weights
        allowed_models: Models this blueprint can use
        default_model: Preferred model
        temperature: Default temperature
        tools: List of enabled tool names
        quality_tier: Default quality tier (light/standard/full)
        rag_enabled: Whether RAG context injection is enabled
        max_retries: Max validation retries
        metadata: Additional key-value metadata
        created_at: Creation timestamp
        updated_at: Last modification timestamp
    """

    id: str = ""
    tenant_id: str = ""
    version: int = 1
    name: str = "default"

    # Persona & behavior
    persona: str = "You are a helpful AI assistant."
    system_prompt: str = ""
    priority_weights: PriorityWeights = Field(default_factory=PriorityWeights)

    # Model & execution
    allowed_models: list[str] = Field(default_factory=lambda: [
        "claude-sonnet-4-20250514", "gpt-4o", "gpt-4o-mini",
    ])
    default_model: str = "claude-sonnet-4-20250514"
    temperature: float = 0.7
    tools: list[str] = Field(default_factory=list)
    quality_tier: str = "standard"
    rag_enabled: bool = True
    max_retries: int = 1

    # Metadata
    metadata: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    def to_runnable_config(self) -> dict[str, Any]:
        """Convert blueprint to LangGraph RunnableConfig configurable dict.

        This is the bridge between Lifecycle and Execution layers.
        """
        return {
            "configurable": {
                "blueprint_id": self.id,
                "blueprint_version": self.version,
                "default_model": self.default_model,
                "allowed_models": self.allowed_models,
                "system_prompt_override": self.system_prompt or self.persona,
                "quality_tier": self.quality_tier,
                "priority_weights": self.priority_weights.to_dict(),
                "tools": self.tools,
                "rag_enabled": self.rag_enabled,
                "max_retries": self.max_retries,
                "temperature": self.temperature,
            }
        }

    def to_supabase_row(self) -> dict[str, Any]:
        """Serialize to Supabase-compatible row."""
        return {
            "id": self.id,
            "tenant_id": self.tenant_id,
            "version": self.version,
            "name": self.name,
            "persona": self.persona,
            "system_prompt": self.system_prompt,
            "priority_weights": self.priority_weights.to_dict(),
            "allowed_models": self.allowed_models,
            "default_model": self.default_model,
            "temperature": self.temperature,
            "tools": self.tools,
            "quality_tier": self.quality_tier,
            "rag_enabled": self.rag_enabled,
            "max_retries": self.max_retries,
            "metadata": self.metadata,
        }

    @classmethod
    def from_supabase_row(cls, row: dict[str, Any]) -> AgentBlueprint:
        """Deserialize from Supabase row."""
        weights = row.get("priority_weights", {})
        return cls(
            id=row.get("id", ""),
            tenant_id=row.get("tenant_id", ""),
            version=row.get("version", 1),
            name=row.get("name", "default"),
            persona=row.get("persona", ""),
            system_prompt=row.get("system_prompt", ""),
            priority_weights=PriorityWeights(**weights) if weights else PriorityWeights(),
            allowed_models=row.get("allowed_models", []),
            default_model=row.get("default_model", "claude-sonnet-4-20250514"),
            temperature=row.get("temperature", 0.7),
            tools=row.get("tools", []),
            quality_tier=row.get("quality_tier", "standard"),
            rag_enabled=row.get("rag_enabled", True),
            max_retries=row.get("max_retries", 1),
            metadata=row.get("metadata", {}),
        )

    @classmethod
    def default(cls, tenant_id: str = "") -> AgentBlueprint:
        """Create a default blueprint for a tenant."""
        import uuid
        return cls(
            id=str(uuid.uuid4()),
            tenant_id=tenant_id,
            name="default",
        )
